export const GET_POLLS = 'GET_POLLS'
export const ADD_NEW_POLL = 'ADD_NEW_POLL'
export const GET_ONE_POLL = 'GET_ONE_POLL'
export const VOTE = 'VOTE'
export const ADD_ANSWER_TO_POLL = 'ADD_ANSWER_TO_POLL'
export const DELETE_POLL = 'DELETE_POLL'
export const CHANGE_STATUS = 'CHANGE_STATUS'
export const ALREADY_VOTED = 'ALREADY_VOTED'
